import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const poppinRegular = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins-regular",
  weight: "400",
});

const poppinLight = localFont({
  src: "./fonts/Poppins-Light.ttf",
  variable: "--font-poppins-light",
  weight: "300",
});

const poppinMedium = localFont({
  src: "./fonts/Poppins-Medium.ttf",
  variable: "--font-poppins-medium",
  weight: "500",
});

const poppinSemibold = localFont({
  src: "./fonts/Poppins-Semibold.ttf",
  variable: "--font-poppins-semibold",
  weight: "600",
});

const poppinBold = localFont({
  src: "./fonts/Poppins-Bold.ttf",
  variable: "--font-poppins-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${poppinRegular.variable} 
          ${poppinLight.variable} 
          ${poppinMedium.variable} 
          ${poppinSemibold.variable} 
          ${poppinBold.variable} 
          antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
